Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Python39\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python39\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python39\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Python39\lib\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "C:\Python39\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Python39\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import numpy as np
from pandas import ExcelWriter
from pandas import ExcelFile
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import os
from supervised.automl import AutoML

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_18788/3999718835.py[0m in [0;36m<module>[1;34m[0m
[0;32m      6[0m [1;32mfrom[0m [0msklearn[0m[1;33m.[0m[0mmodel_selection[0m [1;32mimport[0m [0mtrain_test_split[0m[1;33m[0m[1;33m[0m[0m
[0;32m      7[0m [1;32mimport[0m [0mos[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 8[1;33m [1;32mfrom[0m [0msupervised[0m[1;33m.[0m[0mautoml[0m [1;32mimport[0m [0mAutoML[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      9[0m [1;33m[0m[0m
[0;32m     10[0m [1;32mfrom[0m [0msklearn[0m[1;33m.[0m[0mmetrics[0m [1;32mimport[0m [0maccuracy_score[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'supervised'
ModuleNotFoundError: No module named 'supervised'

